name: "Build & test"

on:
  push:
    branches:
    - main
    - master
  pull_request:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

env:
  go_version: "^1.20"

jobs:
  test:
    name: "Test [${{ matrix.os }}]"

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macOS-latest

    runs-on: ${{ matrix.os }}

    steps:

    - name: "Checkout"
      uses: actions/checkout@v3

    - name: "Setup Go"
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.go_version }}
        cache: true

    - name: "Test project"
      run: make test

  lint:
    name: "Lint [${{ matrix.os }}]"

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        # - windows-latest # Reenable windows linting when issue with gofmt is resolved
        - macOS-latest

    runs-on: ${{ matrix.os }}

    steps:

    - name: "Checkout"
      uses: actions/checkout@v3

    - name: "Setup Go"
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.go_version }}
        cache: true

    - name: "Lint Go code"
      uses: golangci/golangci-lint-action@v8
      with:
        verify: true
        version: latest

  check_go_mod_tidy:
    name: "Check `go mod tidy`"

    runs-on: "ubuntu-latest"

    steps:

    - name: "Checkout"
      uses: actions/checkout@v3

    - name: "Setup Go"
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.go_version }}
        cache: true

    - name: "Check if `go mod tidy` has been run properly"
      run: |
        make dependencies
        if ! (git update-index --refresh > /dev/null && git diff-index --quiet HEAD --); then
          echo 'ERROR: go.mod file is outdated.' >&2
          echo 'Please update go.mod file by running' >&2
          echo '    make dependencies' >&2
          echo 'in the root of the repository before committing changes.' >&2
        fi

  check_tools_go_mod_tidy:
    name: "Check tools `go mod tidy`"

    runs-on: "ubuntu-latest"

    steps:

    - name: "Checkout"
      uses: actions/checkout@v3

    - name: "Setup Go"
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.go_version }}
        cache: true

    - name: "Check if `go mod tidy` has been run properly for tools"
      run: |
        make tools/dependencies
        if ! (git update-index --refresh > /dev/null && git diff-index --quiet HEAD --); then
          echo 'ERROR: Tools go.mod file is outdated.' >&2
          echo 'Please update tools go.mod file by running' >&2
          echo '    make tools/dependencies' >&2
          echo 'in the root of the repository before committing changes.' >&2
        fi

  check_proto_generated_code:
    name: "Check protobuf generated code"

    runs-on: "ubuntu-latest"

    steps:

    - name: "Checkout"
      uses: actions/checkout@v3

    - name: "Setup Go"
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.go_version }}
        cache: true

    - name: "Check if proto definition are properly generated"
      run: |
        make proto
        if ! (git update-index --refresh > /dev/null && git diff-index --quiet HEAD --); then
          echo 'ERROR: Proto definitions are outdated.' >&2
          echo 'Please generate proto definitions by running' >&2
          echo '    make proto' >&2
          echo 'in the root of the repository before committing changes.' >&2
        fi

  build:
    name: "Build [${{ matrix.GOOS }}/${{ matrix.GOARCH }}]"

    strategy:
      fail-fast: false
      matrix:
        GOOS:
        - linux
        - windows
        - darwin
        GOARCH:
        - amd64
        - arm64

    runs-on: ubuntu-latest

    steps:

    - name: "Checkout"
      uses: actions/checkout@v3

    - name: "Setup Go"
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.go_version }}
        cache: true

    - name: "Extract version"
      id: get_version
      uses: battila7/get-version-action@v2

    - name: "Generate version information"
      run: |
        GIT_TAG="0.0.0-dev+$(date '+%Y%m%d%H%M%S')"
        if [[ "${{ steps.get_version.outputs.is-semver }}" == "true" ]]; then
          GIT_TAG="${{ steps.get_version.outputs.version-without-v }}"
        fi
        GIT_COMMIT=$(git rev-parse HEAD)

        echo "GIT_TAG=$GIT_TAG"
        echo "GIT_TAG=$GIT_TAG" >> $GITHUB_ENV
        echo "GIT_COMMIT=$GIT_COMMIT"
        echo "GIT_COMMIT=$GIT_COMMIT" >> $GITHUB_ENV

    - name: "Build project [${{ matrix.GOOS }}/${{ matrix.GOARCH }}]"
      run: |
        mkdir -p dist
        GOOS=${{ matrix.GOOS }} GOARCH=${{ matrix.GOARCH }} go build \
          -ldflags="-X 'main.Version=$GIT_TAG' -X 'main.Commit=$GIT_COMMIT'" \
          -o dist/gitidentity-${{ matrix.GOOS }}-${{ matrix.GOARCH }} \
          -v \
          .

    - name: Archive binaries
      uses: actions/upload-artifact@v4
      with:
        name: gitidentity-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
        path: dist
        retention-days: 5
